module.exports = {
  ENABLE: 1,
  DISABLE: 0,

  HAD: 1,
  CANCEL: 0,

  VERIFY_CODE_TYPE_IMAGE: 1,
  VERIFY_CODE_TYPE_SMS: 2,
  VERIFY_CODE_SENDSTATUS_UNSEND: 0,
  VERIFY_CODE_SENDSTATUS_SUCCESS: 1,
  VERIFY_CODE_SENDSTATUS_FAIL: 2,

  CONDITION_TYPE_IMAGE: 1,
  CONDITION_TYPE_VIDEO: 2,
  CONDITION_TYPE_AUDIO: 3,

}